import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { addActivity, canEdit, currentList, data, escape } from "../todo-data.js";
import { now } from "../time.js";

registerMainMenuItem({ label: "My tasks", data: "task:list", order: 30 });
registerMainMenuItem({ label: "Activity", data: "activity:show", order: 60 });
registerMainMenuItem({ label: "Settings", data: "settings:show", order: 70 });
const composer = new Composer<Ctx>();

function actions(taskId: string) { return inlineKeyboard([[inlineButton("Assign", `task:assign:${taskId}`), inlineButton("Complete", `task:done:${taskId}`)], [inlineButton("Add comment", `task:comment:${taskId}`)], [inlineButton("Back to menu", "menu:main")]]); }
function taskText(title: string, status: string, due?: string) { return `${status === "done" ? "Done" : "Open"}: ${escape(title)}${due ? `\nDue: ${due.slice(0, 10)}` : ""}`; }

composer.callbackQuery("task:list", async (ctx) => {
  await ctx.answerCallbackQuery(); const store = data(ctx); const list = currentList(store);
  const tasks = list.taskIds.map((id) => store.tasks[id]).filter(Boolean);
  if (!tasks.length) { await ctx.editMessageText(`No tasks in “${list.name}” yet — tap Add task to create one.`, { reply_markup: inlineKeyboard([[inlineButton("Add task", "task:add")], [inlineButton("Back to menu", "menu:main")]]) }); return; }
  await ctx.editMessageText(`Tasks in “${list.name}”`, { reply_markup: inlineKeyboard([...tasks.slice(0, 6).map((t) => [inlineButton(taskText(t.title, t.status, t.dueDate).slice(0, 45), `task:view:${t.id}`)]), [inlineButton("Add task", "task:add")], [inlineButton("Back to menu", "menu:main")]]) });
});
composer.callbackQuery(/^task:view:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const task = data(ctx).tasks[ctx.match[1]]; if (!task) { await ctx.editMessageText("That task is no longer available."); return; } await ctx.editMessageText(`${taskText(task.title, task.status, task.dueDate)}${task.description ? `\n${escape(task.description)}` : ""}`, { reply_markup: actions(task.id) }); });
composer.callbackQuery(/^task:done:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); const task = store.tasks[ctx.match[1]]; if (!task) { await ctx.editMessageText("That task is no longer available."); return; } const list = store.lists[task.listId]; if (!canEdit(list, store.user.chatId)) { await ctx.editMessageText("This list is read-only for you. Ask an admin for edit access."); return; } task.status = "done"; addActivity(store, list.id, store.user.chatId, `completed “${task.title}”`); await ctx.editMessageText(`Marked “${escape(task.title)}” complete.`, { reply_markup: actions(task.id) }); await notify(ctx, task.assigneeId, `“${task.title}” was marked complete.`); });
composer.callbackQuery(/^task:assign:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); const task = store.tasks[ctx.match[1]]; if (!task) { await ctx.editMessageText("That task is no longer available."); return; } const list = store.lists[task.listId]; if (!canEdit(list, store.user.chatId)) { await ctx.editMessageText("This list is read-only for you. Ask an admin for edit access."); return; } if (list.members.length < 2) { await ctx.editMessageText("No teammates are on this list yet — share an invite first."); return; } await ctx.editMessageText("Choose an assignee.", { reply_markup: inlineKeyboard([...list.members.map((m) => [inlineButton(m.name.slice(0, 30), `task:assignee:${task.id}:${m.id}`)]), [inlineButton("Back", `task:view:${task.id}`)]]) }); });
composer.callbackQuery(/^task:assignee:([^:]+):(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); const task = store.tasks[ctx.match[1]]; if (!task) { await ctx.editMessageText("That task is no longer available."); return; } const member = store.lists[task.listId].members.find((m) => m.id === Number(ctx.match[2])); if (!member) { await ctx.editMessageText("That teammate is no longer on this list."); return; } task.assigneeId = member.id; addActivity(store, task.listId, store.user.chatId, `assigned “${task.title}” to ${member.name}`); await ctx.editMessageText(`Assigned “${escape(task.title)}” to ${escape(member.name)}.`, { reply_markup: actions(task.id) }); await notify(ctx, member.chatId, `You were assigned “${task.title}”.`); });
composer.callbackQuery(/^task:comment:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); if (!store.tasks[ctx.match[1]]) { await ctx.editMessageText("That task is no longer available."); return; } store.flow = { kind: "comment", taskId: ctx.match[1] }; await ctx.editMessageText("Write your comment.", { reply_markup: { force_reply: true, input_field_placeholder: "Add a helpful note" } as never }); });
composer.on("message:text", async (ctx, next) => { const store = data(ctx); if (store.flow?.kind !== "comment") return next(); const task = store.flow.taskId ? store.tasks[store.flow.taskId] : undefined; const text = ctx.message.text.trim(); if (!task || !text) { await ctx.reply("Write a short comment, then try again."); return; } task.comments.push({ authorId: store.user.chatId, authorName: store.user.name, text, timestamp: now().toISOString() }); addActivity(store, task.listId, store.user.chatId, `commented on “${task.title}”`); store.flow = undefined; await ctx.reply("Comment added.", { reply_markup: actions(task.id) }); });
composer.callbackQuery("activity:show", async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); const list = currentList(store); const entries = store.activity[list.id] ?? []; if (!entries.length) { await ctx.editMessageText("No activity yet — changes to this list will appear here.", { reply_markup: inlineKeyboard([[inlineButton("Back to menu", "menu:main")]]) }); return; } await ctx.editMessageText(`Recent activity in “${list.name}”\n\n${entries.slice(-10).reverse().map((e) => `• ${e.action}`).join("\n")}`, { reply_markup: inlineKeyboard([[inlineButton("Back to menu", "menu:main")]]) }); });
composer.callbackQuery("settings:show", async (ctx) => { await ctx.answerCallbackQuery(); const enabled = data(ctx).notifications; await ctx.editMessageText(`Task notifications are ${enabled ? "on" : "off"}.`, { reply_markup: inlineKeyboard([[inlineButton(enabled ? "Turn off" : "Turn on", "settings:notifications")], [inlineButton("Back to menu", "menu:main")]]) }); });
composer.callbackQuery("settings:notifications", async (ctx) => { await ctx.answerCallbackQuery(); const store = data(ctx); store.notifications = !store.notifications; await ctx.editMessageText(`Task notifications are now ${store.notifications ? "on" : "off"}.`, { reply_markup: inlineKeyboard([[inlineButton("Back to settings", "settings:show")]]) }); });

async function notify(ctx: Ctx, chatId: number | undefined, text: string): Promise<void> { if (!chatId || chatId === ctx.chat?.id || !data(ctx).notifications) return; try { await ctx.api.sendMessage(chatId, text, { reply_markup: inlineKeyboard([[inlineButton("Open my tasks", "task:list")]]) }); } catch { /* Users can revoke Telegram consent; a notification must not abort the update. */ } }
export default composer;
